### ISSUE TITLE
Wiki example: download PDF from DOI

### ISSUE THREAD

**Issue by Metasoliton** [fabiobatalha/crossrefapi#19]
Hi there, great work!!!

I am a first-time user, trying to wrap my head around dowloading a PDF based on its DOI, something like 
works.doi.download('10.1590/0102-311x00133115', '~/Downloads/')
that would result in the PDF landing in my Downloads folder.

I guess this is something very simple, however I could not find any example. Would you please provide one, perhaps even as a Wiki entry? 

Many thanks & Merry Christmas,
Stav

**Comment by Ankush-Chander** [comment]
Hi @Metasoliton,
I hope it"s not too late to reply.
This api is primarily for looking up data via crossref api. Download url is not necessarily provided by crossref api.
However there are alternate solutions which can be found [here](https://github.com/search?q=download+doi).

Let us know if we can close this issue.

@fabiobatalha

**Comment by fabiobatalha** [comment]
Hello @Ankush-Chander 

Yes, we can close this issue.
