### ISSUE TITLE
Multiple words in query

### ISSUE THREAD

**Issue by fahdi104** [fabiobatalha/crossrefapi#20]
How to do query with multiple words? I use "+" but the results that I got from Crossref website is different than using crossrefapi?

**Comment by fabiobatalha** [comment]
Hello @fahdi104 

Can you include the string you are using in both queries (Using the website and crossrefapi) in this issue?

**Comment by CNGaoWenbo** [comment]
What's the grammar of multiple query? Can you give a code example?

**Comment by BananaTonic** [comment]
You can do query with multiple words using the list, as following example.

```
works = Works()
res = works.query(bibliographic=[keyword1,keyword2,keyword3])
```

**Comment by CNGaoWenbo** [comment]
@BananaTonic 
It works, thank you!
Though it seems to be equivalent to OR relationship among the keywords.

**Comment by moeinj9** [comment]
I also would like to use this feature, but I need the equivalent of AND relationship between the query terms. For example, curcumin AND carcinoma. Please advise. Thanks!

**Comment by chrisoutwright** [comment]
I am also getting nonsensical results by using author and tile of the paper:
`works.query(bibliographic='Context-aware natural language generation for spoken dialogue systems').filter(from_online_pub_date='2016').query(author='Zhou')`

Gets me results like: _Synthesis of Biomass‐Derived Carbon Induced by Cellular Respiration in Yeast for Supercapacitor Applications_ . A boolean and should be implemented for it.

**Comment by fabiobatalha** [comment]
Those improvements must be done in Crossref API Server, the client will reflect the improvements once they are available in the Crossref API Server.
