### ISSUE TITLE
works.filter() and more than 1000 results

### ISSUE THREAD

**Issue by tdbowman** [fabiobatalha/crossrefapi#21]
I'm using the filter ('for i in works.filter()') and selecting journal (using ISSN) and one month date period to gather articles (using from-pub-date and until-pub-date) from same issue/volume of journal. This seems to work, but when there are more than 1000 records I receive error "Expecting value: line 1 column 1 (char 0)" when using 'json.dumps(i)' and it kills my code.

I can't figure out why this is happening?  Any ideas?

**Comment by fabiobatalha** [comment]
Hello @tdbowman 

Can you include in this issue the filter you are attempting to do?
