### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by CNGaoWenbo** [fabiobatalha/crossrefapi#22]
I am a fresh user, when applying syntax
w1 = works.query(title='zika')
return
TypeError: list indices must be integers or slices, not str
But it is OK when query author and others, have any ideas?

**Comment by fabiobatalha** [comment]
Hi @CNGaoWenbo 

The field title is deprecated in Crossref API.

The recommendation is to use the field **bibliographic**

w1 = works.query(bibliographic='zika')

I will remove the mentions for the field **title** from the documentation.

**Comment by fabiobatalha** [comment]
Fixed in version : https://github.com/fabiobatalha/crossrefapi/releases/tag/1.4.0

**Comment by CNGaoWenbo** [comment]
@fabiobatalha Thanks
