### ISSUE TITLE
Too Many Requests Error

### ISSUE THREAD

**Issue by ManivannanIkomet** [fabiobatalha/crossrefapi#25]
Hi @fabiobatalha 
I am using this library now and i got too many request error.
Because i called the multiple request at a time.
How to handle this error
Please reply me.

**Comment by ManivannanIkomet** [comment]
Hi @fabiobatalha 
Please reply me.

**Comment by fabiobatalha** [comment]
Hi @ManivannanIkomet Sorry not to answer you earlier, I was offline these days.

The too many requests is retrieved by the Crossref API. Are you using the polite mode?

https://github.com/fabiobatalha/crossrefapi#support-for-polite-requests-etiquette

Can you send the code you have written. I will take a look on it.

**Comment by ManivannanIkomet** [comment]
Hi @fabiobatalha ,
Thank you for your responce. I didn't use polite mode.
I will send you my code
