### ISSUE TITLE
Metadata plus support?

### ISSUE THREAD

**Issue by Ankush-Chander** [fabiobatalha/crossrefapi#27]
Does this api support passing of metadata plus api token?

**Comment by fabiobatalha** [comment]
Are you intending to use the API for DOI registering?

**Comment by Ankush-Chander** [comment]
I intend to use the api to fetch metadata of a document  based on doi.

**Comment by fabiobatalha** [comment]
There is no API token tokens in this API. 

To collect metadata using DOI, see:

https://github.com/fabiobatalha/crossrefapi/blob/master/README.rst#doi

**Comment by Ankush-Chander** [comment]
"Metadata Plus gives you enhanced access to all our supported APIs, guarantees service levels and support, and additional features such as snapshots and priority service/rate limits."

Users can avail "Metadata Plus" features by passing "Crossref-Plus-API-Token" in request headers.

I created a pull request for the same.
Please review.

https://github.com/fabiobatalha/crossrefapi/pull/28

**Comment by Ankush-Chander** [comment]
Hi, 
How do we make  pypi point to latest version?
https://pypi.org/project/crossrefapi/#history

**Comment by fabiobatalha** [comment]
Hi @Ankush-Chander 

It was uploaded to PyPi under version 1.5.0

**Comment by Ankush-Chander** [comment]
Thank you. I appreciate your work in making crossref API more accessible through this project.

**Comment by fabiobatalha** [comment]
thank you for the contribution!
