### ISSUE TITLE
Could one use the crossrefapi to construct an author search with both first and last name?

### ISSUE THREAD

**Issue by russelljjarvis** [fabiobatalha/crossrefapi#30]
Could one use the crossrefapi to construct an author search with both first and last name?

I have tried that a bit but the results are very imprecise.

**Comment by fabiobatalha** [comment]
Hello @russelljjarvis 

Can you give an example of your attempts?

**Comment by russelljjarvis** [comment]
Sorry yes,

NAME is a string first name, last name, separated by " ", and entered from a GUI.

https://github.com/russelljjarvis/ScienceAccess/blob/master/science_access/online_app_backend.py#L182-L186

```python
        queries = {'query.author': NAME}
        ar = []
        bi =[p for p in iterate_publications_as_json(max_results=100, queries=queries)]   
        for p in bi[0:9]:    
            res = str('https://api.unpaywall.org/v2/')+str(p['DOI'])+str('?email=YOUR_EMAIL')
````

**Comment by russelljjarvis** [comment]
I just updated the file.
For example if NAME="Patrick McGurrin"
Do you think the problem is that I am not filtering the result enough? Like 

If I restrict the year 
 https://github.com/russelljjarvis/ScienceAccess/blob/master/science_access/online_app_backend.py#L203
```python
   works = Works()
   ww =  works.query(author=NAME).filter(from_online_pub_date='2000')
```       
@mcgurrgurr

**Comment by fabiobatalha** [comment]
hello @russelljjarvis 

You should use the ORCID API : https://orcid.org/organizations/integrators/API
