### ISSUE TITLE
ReadTimeout: HTTPSConnectionPool(host='api.crossref.org', port=443): Read timed out. (read timeout=10)

### ISSUE THREAD

**Issue by Keramatfar** [fabiobatalha/crossrefapi#31]
Hi,
I checked the package from different computers and consistently get:
ReadTimeout: HTTPSConnectionPool(host='api.crossref.org', port=443): Read timed out. (read timeout=10).

**Comment by jesusce94** [comment]
Same issue here. I did execute the exact same code before and it did work finely.

**Comment by fabiobatalha** [comment]
Ok, I will check it myself and give a feedback asap.

**Comment by lynguistical** [comment]
> Ok, I will check it myself and give a feedback asap.

Any results on this? I need to use the API asap :(
