### ISSUE TITLE
[Question] Is there a way to get Abstract?

### ISSUE THREAD

**Issue by santoshbs** [fabiobatalha/crossrefapi#33]
I was wondering if the library allows to fetch only works that have an abstract and if there way to fetch abstract.

**Comment by fabiobatalha** [comment]
Yes it is possible.

works.find(has_abstract='true')

The abstract will be available in the response (JSON) in the attribute "abstract".

It seems the use of has_abstract lead to lots of request timeout errors, it is something to be reported to the Crossref team.
