### ISSUE TITLE
New Crossref REST API coming soon

### ISSUE THREAD

**Issue by ppolischuk** [fabiobatalha/crossrefapi#37]
Hi, 

Thank you for maintaining one of the documented libraries for using the Crossref REST API.

We’ve been working on a new version of the REST API, replacing the Solr backend with Elasticsearch and moving from our own hardware in a datacenter to a cloud platform.

We plan to cutover to the new version shortly (expect an official announcement on our blog in the next few days with more details), and wanted to invite you to test it out before the official cutover.

Please check it out at [https://api.production.crossref.org/](https://api.production.crossref.org/)

During the cutover phase (expected to last a few weeks), traffic will be redirected to the above domain on a pool by pool basis. Once all traffic is using the new service, we will continue to use the `api.crossref.org` domain, so please do not update anything to use the temporary domain.

Let me know if you have any questions. Issues can be filed into our [GitLab issue repository](https://gitlab.com/crossref/issues/issues/), or I’ll keep an eye on this thread.

Thanks again,
Patrick

**Comment by fabiobatalha** [comment]
Parameter **rows** is not working for journals, ex:

https://api.production.crossref.org/journals/0102-311X/works?query=zika&rows=0

**Comment by fabiobatalha** [comment]
The only problem found was reported to crossref.

**Comment by ppolischuk** [comment]
Thank you much. It looks like the rows parameter works properly in your query for values greater than 0. Not sure why `rows=0` returns `Resource not found.` We'll look into it.

**Comment by ppolischuk** [comment]
I hadn't yet seen your Gitlab issue. Thanks for filing that. I'll reconcile the two and close one as a duplicate.
