### ISSUE TITLE
full-text.application filter error

### ISSUE THREAD

**Issue by RichardScottOZ** [fabiobatalha/crossrefapi#45]
When I try

![image](https://user-images.githubusercontent.com/72196131/182960368-d332e141-dd83-4db7-8197-cb1788259a8e.png)

Same with an "_" as in some examples.

```python
works.filter(has_full_text='true').query('zika').count()
```

is fine though

**Comment by RichardScottOZ** [comment]
Also, thanks very much for this, very nice!

**Comment by Ankush-Chander** [comment]
Hi @RichardScottOZ 
Thanks for trying out `crossrefapi`.

`.` and `-` are not supported in the argument hence we follow the notation where `dot` is replaced by `double_underscore` and `dash` is replaced by  `underscore`.

Following snippet shopuld work for you as intended:
```
from crossref.restful import Works
work = Works()
for i in work.filter(full_text__application="text-mining"): # url: https://api.crossref.org/works?filter=full-text.application%3Atext-mining
	print(i)
		
```

**Comment by RichardScottOZ** [comment]
Thanks very much!

![image](https://user-images.githubusercontent.com/72196131/183219987-40dfa338-93df-46bb-a4b1-9b5b3d4d5461.png)
