### ISSUE TITLE
It seems that a lot of  literature doesn't exist abstracts in crossref

### ISSUE THREAD

**Issue by code-isnot-cold** [fabiobatalha/crossrefapi#47]
I have got 10000+ Wiley dois by crossref API( works.query() without "has_abstract=true", cuz it returns 0 with "has_abstract=true" ) and tried two different ways to fetch abstracts, but they don't work.
If I tried to fetch abstracts by Wiley API, it would download  full texts(PDF), which wastes a lot of time in parsing.
So how can I get abstracts by crossref or does crossref not have abstracts of these dois? 
Thanks for your help!
There are my approaches to fetch abstracts:
1.from crossref.restful import Works API:
![image](https://user-images.githubusercontent.com/105880123/208823344-f80e9cf8-a4b8-4a7c-8563-5864492055ba.png)
2."requests" tool to link crossref url:
 
![image](https://user-images.githubusercontent.com/105880123/208823818-a3dae5ea-f5cd-4814-a268-1b21bed7c77e.png)

**Comment by fabiobatalha** [comment]
Hello @code-isnot-cold 

Unfortunately, Wiley is not providing abstracts to Crossref as we can see in the Crossref Participation Reports.

![Screenshot from 2022-12-21 13-30-12](https://user-images.githubusercontent.com/504142/208978158-3f04e89e-65c4-4759-8551-2f1f35edb08f.png)

The url used to retrieve the report is: https://www.crossref.org/members/prep/
