### ISSUE TITLE
Depositor missing 'timeout' attribute used with self.do_http_request

### ISSUE THREAD

**Issue by nausicaa-rose** [fabiobatalha/crossrefapi#64]
Hello,
I've found your library useful, but encountered a bug recently. `crossref.restful.Depositor` has several methods that expect to pass the the attribute `self.timeout` as a parameter to `self.do_http_request`, which throws this error:  "AttributeError: 'Depositor' object has no attribute 'timeout'" because `self.timeout` is never initialized.

I did a quick patch by adding `timeout=100` to `Depositor.__init__()`'s parameter list and adding `self.timeout = timeout` in the body of the init, which fixed the issue, at least in my very cursory testing.

If the above is an acceptable solution, I'm happy to test it out more thoroughly and submit a pull request. If you'd prefer another approach, I'd be happy to help with that as well.

Thanks for creating and maintaining this library!

**Comment by fabiobatalha** [comment]
hello @nausicaa-rose sorry for the delay in answer you. Yes, you can submit a MR.

**Comment by Engerrs** [comment]
Hi @fabiobatalha , do you please clarify when the provided PR will be merged, as I got same errors while trying to Deposit my xml. I can temporary extract the logic from the methods that have this issue right into my code as a temporary workaround to make it work, but it would be much better, if the provided PR will be reviewed and merged.

**Comment by fabiobatalha** [comment]
I will look into this and get back to you today

**Comment by fabiobatalha** [comment]
Hello @nausicaa-rose and @Engerrs, sorry about the delay. The new version is available 1.6.1.
