### ISSUE TITLE
support for select parameter

### ISSUE THREAD

**Issue by gbilder** [fabiobatalha/crossrefapi#7]
We have added a `select` parameter that allows one finer control of response sizes. The following, for example, will only return the DOI and title for each matching record.

`http://api.crossref.org/works?sample=10&select=DOI,title`

**Comment by fabiobatalha** [comment]
@gbilder 

What is your suggestions of use?

eg 1:

Works().select(['DOI', 'title'])

eg 2:

Works().select('DOI', 'title')

eg 3:

Works().select('DOI').select('title')

eg 4:

Works().select('DOI, title')

eg 5:

support all of the previous samples
