### ISSUE TITLE
Please add Depositor example to Readme.md

### ISSUE THREAD

**Issue by sjtower** [fabiobatalha/crossrefapi#9]
I'm interested in using this project to do deposits into crossref. Could you add an example of how to use the Depositor class? 

Also, does the Depositor support resource-only deposits?

Thanks!

**Comment by fabiobatalha** [comment]
hello @sjtower 

I will include an example asap.

The depositor class implements the operation "doMDUpload".

https://support.crossref.org/hc/en-us/articles/214960123

**Comment by fabiobatalha** [comment]
Done!
